### PR TITLE
Fix async issue

### PR DESCRIPTION
**Pull request by nschimme**
Resolves https://github.com/nikshriv/cync_lights/issues/94

### CODE REVIEW

**Comment by nschimme** [comment]
@nikshriv please merge

**Comment by Lioncat6** [comment]
The author hasn't touched their github account since March 2023 🥲

**Comment by web250** [comment]
@nschimme how do I initiate the changes once I've edited the 4 py files? (edited in VI via HA terminal)

**Comment by eczuckerman** [comment]
Can somebody walk me through how to fix this? It is driving me nuts.

**Comment by web250** [comment]
> Can somebody walk me through how to fix this? It is driving me nuts.

Check this link: https://github.com/nikshriv/cync_lights/pull/95/commits/0652efd204513285796ac08bad3d9de7f2c67207
You need to make edits (using Terminal in HA) using your text editor of choice (I used vi, nano works too)
Edit 4 files, and change the red to the green. The numbers on the left are the line numbers in the code.

**Review by garciarx — APPROVED** [review]

**Pull request merged**
